### ISSUE TITLE
How can i get the dataset?

### ISSUE THREAD

**Issue by Anson1013** [DavidBoja/Landmarks2Anthropometry#2]
How can I get in touch with you? I have some questions I'd like to ask you

**Comment by Anson1013** [comment]
How can I get in touch with you? I have some questions I'd like to ask you.

**Comment by DavidBoja** [comment]
You can ask me questions here or add me on LinkedIn.
Regarding the dataset - you can take a look [here](https://bodysizeshape.com/page-1855750).

**Comment by Anson1013** [comment]
thank you!i want to know how to traing by using myself dataset

**Comment by DavidBoja** [comment]
We use a Bayesian ridge regression model from [sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.BayesianRidge.html) to train the model. We use the landmark coordinates as input to the model (so if you're using 72 body landmarks, this means that the input to the model is a 72*3=216 numbers) and the measurements as the output to the model. 
Since the Bayesian Ridge Regression can only estimate a single scalar output, we train 11 different models for each of the 11 measurements.

You can find more details in our paper [here](https://www.scitepress.org/publishedPapers/2024/123840/pdf/index.html).
